# -*- coding: utf-8 -*-
"""
sync_action_parsers.py
Use discovered Go structs to align Rust action parser files:
- core/src/retroproto_parsers/generated/actions/GameAction_*.rs
- core/src/retroproto_parsers/generated/actions/CliAction_*.rs

Actions:
- Ensure struct fields in Rust match Go order/names (PascalCase in Go => snake_case in Rust).
- Ensure parse functions exist and follow naming convention:
    parse_GameAction_<ID>, parse_CliAction_<ID>
- Parser body: split by ';', assign fields in order, use safe defaults.

Outputs:
- Overwrites only targeted action *.rs files.
- Leaves non-action parsers untouched.
"""
import json, re, os, sys
from pathlib import Path
from datetime import datetime
from typing import List, Dict

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / "tools" / "_cache" / "go_structs.json"
ACTIONS_DIR = ROOT / "core" / "src" / "retroproto_parsers" / "generated" / "actions"

RUST_HEADER = """use serde::{Serialize, Deserialize};
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
"""

STRUCT_TMPL = """pub struct {struct_name} {{
{fields}
}}
"""

FN_TMPL = """pub fn {fn_name}(payload: &str) -> Result<{struct_name}, String> {{
    let parts: Vec<&str> = payload.split(';').collect();
{assign}
    Ok({struct_name} {{
{inits}
    }})
}}
"""

SNAKE_RE = re.compile(r'(?<!^)(?=[A-Z])')

def to_snake(name: str) -> str:
    if not name:
        return name
    return SNAKE_RE.sub('_', name).lower()

def guess_action_structs(go_index: Dict[str, List[dict]]) -> Dict[str, dict]:
    # Look for Go struct names that match action patterns
    out = {}
    for name, defs in go_index.items():
        if name.startswith("GameAction") or name.startswith("CliAction"):
            # Exclude nested or sub-structs (like GameActionsSendActionsActionMovement)
            if name.count('_') <= 1:  # Allow GameActionAck, GameActionCancel, etc.
                # Prefer the longest field list variant (if multiple)
                best = max(defs, key=lambda d: len(d.get("fields", [])))
                out[name] = best
    return out

def render_fields(fields):
    lines = []
    for f in fields:
        rs_name = to_snake(f["name"])
        # Map all to String for now unless a numeric is obvious. Dofus actions vary widely; safer to String.
        # If you want aggressive typing, add heuristics here.
        rty = "String"
        lines.append(f"    pub {rs_name}: {rty},")
    return "\n".join(lines)

def render_assign(struct_name, fields):
    assigns = []
    inits = []
    for idx, f in enumerate(fields):
        rs_name = to_snake(f["name"])
        # safe access from parts
        assigns.append(f"    let {rs_name} = parts.get({idx}).map(|s| s.to_string()).unwrap_or_default();")
        inits.append(f"        {rs_name},")
    return "\n".join(assigns), "\n".join(inits)

def ensure_file(struct_name: str, go_def: dict):
    # Determine filename by struct name
    rs_file = ACTIONS_DIR / f"{struct_name}.rs"
    fn_name = f"parse_{struct_name}"
    # E.g. parse_GameAction_105
    fields = go_def.get("fields", [])
    # Build content
    fields_block = render_fields(fields)
    assigns, inits = render_assign(struct_name, fields)

    body = RUST_HEADER
    body += STRUCT_TMPL.format(struct_name=struct_name, fields=fields_block)
    body += "\n"
    body += FN_TMPL.format(fn_name=fn_name, struct_name=struct_name, assign=assigns, inits=inits)

    # Write if missing or different
    old = rs_file.read_text(encoding="utf-8", errors="ignore") if rs_file.exists() else ""
    if old.strip() != body.strip():
        rs_file.write_text(body, encoding="utf-8")
        return {"file": str(rs_file), "updated": True}
    return {"file": str(rs_file), "updated": False}

def main():
    if not CACHE.exists():
        print(json.dumps({"error":"run go_struct_discovery first"}))
        sys.exit(1)
    data = json.loads(CACHE.read_text(encoding="utf-8"))
    go_index = data.get("by_name", {})
    actions = guess_action_structs(go_index)

    ACTIONS_DIR.mkdir(parents=True, exist_ok=True)

    updates = []
    for name, defn in sorted(actions.items()):
        updates.append(ensure_file(name, defn))

    # Ensure actions/mod.rs exposes modules
    mod = ACTIONS_DIR / "mod.rs"
    lines = []
    for name in sorted(actions):
        lines.append(f"pub mod {name};")
    mod_body = "// @generated by sync_action_parsers.py\n" + "\n".join(lines) + "\n"
    old = mod.read_text(encoding="utf-8", errors="ignore") if mod.exists() else ""
    if old.strip() != mod_body.strip():
        mod.write_text(mod_body, encoding="utf-8")
        mod_updated = True
    else:
        mod_updated = False

    print(json.dumps({
        "ok": True,
        "actions_discovered": len(actions),
        "files_updated": sum(1 for u in updates if u["updated"]),
        "mod_updated": mod_updated
    }))

if __name__ == "__main__":
    main()