import re, sys, json, os, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
GEN_DIR = ROOT / "core" / "src" / "retroproto_parsers" / "generated"
REG_DIR = ROOT / "core" / "src" / "retroproto_parsers"
ACT_DIR = ROOT / "core" / "src" / "retroproto_parsers" / "generated" / "actions"
MOD_GEN = GEN_DIR / "mod.rs"
REG_RS  = REG_DIR / "registry.rs"

def list_stems():
    stems = []
    if GEN_DIR.exists():
        # Only include non-action parsers from main directory
        stems.extend([p.stem for p in GEN_DIR.glob("*.rs") if p.name != "mod.rs" and not p.stem.startswith(("GameAction", "CliAction"))])
    if ACT_DIR.exists():
        stems.extend([p.stem for p in ACT_DIR.glob("*.rs") if p.name != "mod.rs"])
    return sorted(set(stems))  # Remove duplicates

def ensure_derive(p):
    t = p.read_text(encoding="utf-8")
    # Add derive if a public struct exists and no derive present immediately above it
    m = re.search(r'(?m)^\s*pub\s+struct\s+\w+', t)
    if not m:
        return
    # If a derive already appears in the previous non-empty lines, skip
    pre = t[:m.start()]
    last_block = pre.splitlines()
    last_block = [ln for ln in last_block if ln.strip()]
    if last_block and last_block[-1].strip().startswith("#[derive("):
        return
    t = t[:m.start()] + "#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]\n" + t[m.start():]
    p.write_text(t, encoding="utf-8")

def emit_generated_mod(stems):
    lines = ["// AUTO-GENERATED registry", ""]
    
    # Include actions subdirectory first
    if ACT_DIR.exists():
        lines.append("pub mod actions;")
        lines.append("")
    
    # Only include non-action modules from main directory
    main_stems = [s for s in stems if not s.startswith(("GameAction", "CliAction"))]
    lines.extend([f"pub mod {s};" for s in main_stems])
    lines.append("")
    lines.extend([f"pub use {s}::parse_{s};" for s in main_stems])
    
    # Include action parsers from actions directory
    action_stems = [s for s in stems if s.startswith(("GameAction", "CliAction"))]
    if action_stems:
        lines.append("")
        lines.append("// Game Action parsers")
        lines.extend([f"pub use actions::{s}::*;" for s in action_stems])
    
    MOD_GEN.write_text("\n".join(lines) + "\n", encoding="utf-8")

def emit_registry(stems):
    wraps = []
    for s in stems:
        wraps.append(f"""
pub fn wrap_{s}(payload: &str) -> Result<serde_json::Value, String> {{
    match parse_{s}(payload) {{
        Ok(v) => serde_json::to_value(v).map_err(|e| e.to_string()),
        Err(e) => Err(e),
    }}
}}""")
    inserts = [f'    m.insert("{s}", wrap_{s} as ParserFn);' for s in stems]
    # Filter out action parsers from individual imports - they come from actions module
    non_action_stems = [s for s in stems if not s.startswith(("GameAction", "CliAction"))]
    imports = [f'use crate::retroproto_parsers::generated::{s}::parse_{s};' for s in non_action_stems]
    
    # Handwritten overrides (ensure mod is added in Rust side)
    handwritten_overrides = {
        # MessageName: wrapper function name
        "GameActions": "wrap_game_actions",
    }
    
    # Merge overrides last so they win
    for name, path in handwritten_overrides.items():
        inserts.append(f'    m.insert("{name}", {path} as ParserFn);')
    
    # Add wrapper functions for handwritten parsers
    wraps.append("""
pub fn wrap_game_actions(payload: &str) -> Result<serde_json::Value, String> {
    match crate::retroproto_parsers::handwritten::GameActions::parse_game_actions(payload) {
        Ok(v) => serde_json::to_value(v).map_err(|e| e.to_string()),
        Err(e) => Err(e),
    }
}""")
    
    REG_DIR.mkdir(parents=True, exist_ok=True)
    REG_RS.write_text(f"""// @generated by tools/gen_parser_registry.py
use std::collections::HashMap;
use once_cell::sync::Lazy;

pub type ParserFn = fn(&str) -> Result<serde_json::Value, String>;

{chr(10).join(imports)}
use crate::retroproto_parsers::handwritten::GameActions;

{''.join(wraps)}

#[allow(non_upper_case_globals)]
pub static PARSERS: Lazy<HashMap<&'static str, ParserFn>> = Lazy::new(|| {{
    let mut m: HashMap<&'static str, ParserFn> = HashMap::new();
{chr(10).join(inserts)}
    m
}});
""", encoding="utf-8")

def main():
    stems = list_stems()
    # Make sure every generated file has derive so it can serialize to JSON
    for p in GEN_DIR.glob("*.rs"):
        if p.name != "mod.rs":
            ensure_derive(p)
    # Also check actions directory
    if ACT_DIR.exists():
        for p in ACT_DIR.glob("*.rs"):
            if p.name != "mod.rs":
                ensure_derive(p)
    
    emit_generated_mod(stems)
    emit_registry(stems)
    print(json.dumps({"generated_count": len(stems), "actions_count": len([s for s in stems if s.startswith(("GameAction", "CliAction"))])}))

if __name__ == "__main__":
    main()