import re, json, shutil, sys, time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ACTIONS = ROOT / "core" / "src" / "retroproto_parsers" / "generated" / "actions"
REGISTRY = ROOT / "core" / "src" / "retroproto_parsers" / "registry.rs"
MOD = ACTIONS / "mod.rs"
SHIMS = ACTIONS / "shims.rs"

def backup(paths):
    ts = time.strftime("%Y%m%d_%H%M%S")
    bdir = ROOT / ".archive" / f"ACTION_SHIMS_{ts}"
    bdir.mkdir(parents=True, exist_ok=True)
    for p in paths:
        if p.exists():
            dst = bdir / p.relative_to(ROOT)
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, dst)
    return bdir

def find_modules():
    mods = []
    for p in sorted(ACTIONS.glob("*.rs")):
        if p.name in ("mod.rs","shims.rs"): continue
        mods.append(p)
    return mods

# Fixed regex patterns to match the actual function signatures in GameAction files
FN_RE = re.compile(r"pub fn (parse_GameAction_(\d+))\(payload: &str\) -> Result<([A-Za-z0-9_]+), String> \{")
ALT_RE = re.compile(r"fn (parse_GameAction_(\d+))\(payload: &str\) -> Result<([A-Za-z0-9_]+), String> \{")
# Also support snake_case naming
SNAKE_RE = re.compile(r"pub fn (parse_game_action_(\d+))\(payload: &str\) -> Result<([A-Za-z0-9_]+), String> \{")
SNAKE_ALT_RE = re.compile(r"fn (parse_game_action_(\d+))\(payload: &str\) -> Result<([A-Za-z0-9_]+), String> \{")

def discover():
    found = {}  # id -> {module, fn, payload}
    by_id_candidates = {}
    for m in find_modules():
        txt = m.read_text(encoding="utf-8", errors="ignore")
        cands = []
        for rx in (FN_RE, ALT_RE, SNAKE_RE, SNAKE_ALT_RE):
            for g in rx.finditer(txt):
                fn = g.group(1)
                aid = g.group(2)
                payload = g.group(3)
                cands.append((fn, aid, payload))
        for fn, aid, payload in cands:
            arr = by_id_candidates.setdefault(aid, [])
            arr.append((m, fn, payload))
    # choose preferred candidate per id (prefer CamelCase name)
    for aid, arr in by_id_candidates.items():
        arr_sorted = sorted(arr, key=lambda x: (0 if "parse_GameAction_" in x[1] else 1, x[0].name))
        m, fn, payload = arr_sorted[0]
        found[aid] = {"module": m, "fn": fn, "payload": payload}
    return found

def write_shims(found):
    # Build imports by module and wrappers by id
    modules = {}
    for aid, info in found.items():
        modules.setdefault(info["module"].stem, True)

    lines = []
    lines.append("// @generated by ensure_action_shims.py — DO NOT EDIT BY HAND")
    lines.append("#![allow(non_snake_case, unused_imports, dead_code)]")
    for m in sorted(modules.keys()):
        lines.append(f"use super::{m}::*;")
    lines.append("")

    # stable order by numeric id
    for aid in sorted(found.keys(), key=lambda x: int(x)):
        info = found[aid]
        fn = info["fn"]
        payload = info["payload"]
        lines.append(f"pub fn parse_GameAction_{aid}(s: &str) -> Result<{payload}, String> {{")
        lines.append(f"    {fn}(s)")
        lines.append("}")
    SHIMS.write_text("\n".join(lines) + "\n", encoding="utf-8")

def ensure_mod(found):
    # build clean mod.rs with module decls + re-export shims
    mod_decls = []
    for m in sorted({info['module'].stem for info in found.values()}):
        mod_decls.append(f"pub mod {m};")
    body = "\n".join([
        "// @generated by ensure_action_shims.py — DO NOT EDIT BY HAND",
        "#![allow(non_snake_case, dead_code)]",
        *mod_decls,
        "mod shims;",
        "pub use shims::*;",
        ""
    ])
    MOD.write_text(body, encoding="utf-8")

def patch_registry():
    if not REGISTRY.exists():
        return 0, 0
    txt = REGISTRY.read_text(encoding="utf-8")
    orig = txt
    # Normalize imports to point at generated::actions
    txt = re.sub(
        r"crate::retroproto_parsers::generated::actions::[A-Za-z0-9_]+::parse_[Gg]ame[Aa]ction_(\d+)",
        r"crate::retroproto_parsers::generated::actions::parse_GameAction_\1",
        txt
    )
    # Also catch any direct parse_GameAction references missing the path
    txt = re.sub(
        r"(?<![A-Za-z0-9_:])parse_GameAction_(\d+)",
        r"crate::retroproto_parsers::generated::actions::parse_GameAction_\1",
        txt
    )
    if txt != orig:
        REGISTRY.write_text(txt, encoding="utf-8")
    return (len(orig), len(txt))

def main():
    if not ACTIONS.exists():
        print(f"ERROR: actions dir not found: {ACTIONS}")
        sys.exit(2)
    bdir = backup([MOD, SHIMS, REGISTRY])
    found = discover()
    if not found:
        print("WARNING: No GameAction parsers discovered; nothing to shim.")
    write_shims(found)
    ensure_mod(found)
    patch_registry()
    print(json.dumps({
        "actions_found": len(found),
        "backup_dir": str(bdir),
        "shims_written": str(SHIMS),
        "mod_written": str(MOD)
    }, indent=2))

if __name__ == "__main__":
    main()